# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.AttestationStatement do
  @moduledoc """
  AttestationStatement is a single in-toto statement attached to an image.
  """

  @derive JSON.Encoder
  defstruct [
    :Descriptor,
    :PredicateType,
    :Statement
  ]

  @type t :: %__MODULE__{
    :Descriptor => DockerEngineAPI.Model.OciDescriptor.t,
    :PredicateType => String.t,
    :Statement => map() | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Descriptor, :struct, DockerEngineAPI.Model.OciDescriptor)
  end
end
