# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.AuthConfig do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :username,
    :password,
    :serveraddress
  ]

  @type t :: %__MODULE__{
    :username => String.t | nil,
    :password => String.t | nil,
    :serveraddress => String.t | nil
  }

  def decode(value) do
    value
  end
end
