# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.BuildIdentity do
  @moduledoc """
  BuildIdentity contains build reference information if image was created via build.
  """

  @derive JSON.Encoder
  defstruct [
    :Ref,
    :CreatedAt
  ]

  @type t :: %__MODULE__{
    :Ref => String.t | nil,
    :CreatedAt => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end
