# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ClusterVolumeSpecAccessModeAccessibilityRequirements do
  @moduledoc """
  Requirements for the accessible topology of the volume. These fields are optional. For an in-depth description of what these fields mean, see the CSI specification.
  """

  @derive JSON.Encoder
  defstruct [
    :Requisite,
    :Preferred
  ]

  @type t :: %__MODULE__{
    :Requisite => [DockerEngineAPI.Model.Topology.t] | nil,
    :Preferred => [DockerEngineAPI.Model.Topology.t] | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Requisite, :list, DockerEngineAPI.Model.Topology)
     |> Deserializer.deserialize(:Preferred, :list, DockerEngineAPI.Model.Topology)
  end
end
