# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ConfigReference do
  @moduledoc """
  The config-only network source to provide the configuration for this network.
  """

  @derive Jason.Encoder
  defstruct [
    :Network
  ]

  @type t :: %__MODULE__{
    :Network => String.t | nil
  }

  def decode(value) do
    value
  end
end
