# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerPidsStats do
  @moduledoc """
  PidsStats contains Linux-specific stats of a container's process-IDs (PIDs).  This type is Linux-specific and omitted for Windows containers.
  """

  @derive Jason.Encoder
  defstruct [
    :current,
    :limit
  ]

  @type t :: %__MODULE__{
    :current => integer() | nil,
    :limit => integer() | nil
  }

  def decode(value) do
    value
  end
end
