# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerThrottlingData do
  @moduledoc """
  CPU throttling stats of the container.  This type is Linux-specific and omitted for Windows containers.
  """

  @derive Jason.Encoder
  defstruct [
    :periods,
    :throttled_periods,
    :throttled_time
  ]

  @type t :: %__MODULE__{
    :periods => integer() | nil,
    :throttled_periods => integer() | nil,
    :throttled_time => integer() | nil
  }

  def decode(value) do
    value
  end
end
