# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerBlkioStats do
  @moduledoc """
  BlkioStats stores all IO service stats for data read and write.  This type is Linux-specific and holds many fields that are specific to cgroups v1. On a cgroup v2 host, all fields other than `io_service_bytes_recursive` are omitted or `null`.  This type is only populated on Linux and omitted for Windows containers.
  """

  @derive JSON.Encoder
  defstruct [
    :io_service_bytes_recursive,
    :io_serviced_recursive,
    :io_queue_recursive,
    :io_service_time_recursive,
    :io_wait_time_recursive,
    :io_merged_recursive,
    :io_time_recursive,
    :sectors_recursive
  ]

  @type t :: %__MODULE__{
    :io_service_bytes_recursive => [DockerEngineAPI.Model.ContainerBlkioStatEntry.t] | nil,
    :io_serviced_recursive => [DockerEngineAPI.Model.ContainerBlkioStatEntry.t] | nil,
    :io_queue_recursive => [DockerEngineAPI.Model.ContainerBlkioStatEntry.t] | nil,
    :io_service_time_recursive => [DockerEngineAPI.Model.ContainerBlkioStatEntry.t] | nil,
    :io_wait_time_recursive => [DockerEngineAPI.Model.ContainerBlkioStatEntry.t] | nil,
    :io_merged_recursive => [DockerEngineAPI.Model.ContainerBlkioStatEntry.t] | nil,
    :io_time_recursive => [DockerEngineAPI.Model.ContainerBlkioStatEntry.t] | nil,
    :sectors_recursive => [DockerEngineAPI.Model.ContainerBlkioStatEntry.t] | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:io_service_bytes_recursive, :list, DockerEngineAPI.Model.ContainerBlkioStatEntry)
     |> Deserializer.deserialize(:io_serviced_recursive, :list, DockerEngineAPI.Model.ContainerBlkioStatEntry)
     |> Deserializer.deserialize(:io_queue_recursive, :list, DockerEngineAPI.Model.ContainerBlkioStatEntry)
     |> Deserializer.deserialize(:io_service_time_recursive, :list, DockerEngineAPI.Model.ContainerBlkioStatEntry)
     |> Deserializer.deserialize(:io_wait_time_recursive, :list, DockerEngineAPI.Model.ContainerBlkioStatEntry)
     |> Deserializer.deserialize(:io_merged_recursive, :list, DockerEngineAPI.Model.ContainerBlkioStatEntry)
     |> Deserializer.deserialize(:io_time_recursive, :list, DockerEngineAPI.Model.ContainerBlkioStatEntry)
     |> Deserializer.deserialize(:sectors_recursive, :list, DockerEngineAPI.Model.ContainerBlkioStatEntry)
  end
end
