# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainersDiskUsage do
  @moduledoc """
  represents system data usage information for container resources.
  """

  @derive JSON.Encoder
  defstruct [
    :ActiveCount,
    :TotalCount,
    :Reclaimable,
    :TotalSize,
    :Items
  ]

  @type t :: %__MODULE__{
    :ActiveCount => integer() | nil,
    :TotalCount => integer() | nil,
    :Reclaimable => integer() | nil,
    :TotalSize => integer() | nil,
    :Items => [map()] | nil
  }

  def decode(value) do
    value
  end
end
