# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerSummaryHealth do
  @moduledoc """
  Summary of health status  Added in v1.52, before that version all container summary not include Health. After this attribute introduced, it includes containers with no health checks configured, or containers that are not running with none
  """

  @derive JSON.Encoder
  defstruct [
    :Status,
    :FailingStreak
  ]

  @type t :: %__MODULE__{
    :Status => String.t | nil,
    :FailingStreak => integer() | nil
  }

  def decode(value) do
    value
  end
end
