# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerCpuStats do
  @moduledoc """
  CPU related info of the container
  """

  @derive Jason.Encoder
  defstruct [
    :cpu_usage,
    :system_cpu_usage,
    :online_cpus,
    :throttling_data
  ]

  @type t :: %__MODULE__{
    :cpu_usage => DockerEngineAPI.Model.ContainerCpuUsage.t | nil,
    :system_cpu_usage => integer() | nil,
    :online_cpus => integer() | nil,
    :throttling_data => DockerEngineAPI.Model.ContainerThrottlingData.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:cpu_usage, :struct, DockerEngineAPI.Model.ContainerCpuUsage)
     |> Deserializer.deserialize(:throttling_data, :struct, DockerEngineAPI.Model.ContainerThrottlingData)
  end
end
