# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerBlkioStatEntry do
  @moduledoc """
  Blkio stats entry.  This type is Linux-specific and omitted for Windows containers.
  """

  @derive Jason.Encoder
  defstruct [
    :major,
    :minor,
    :op,
    :value
  ]

  @type t :: %__MODULE__{
    :major => integer() | nil,
    :minor => integer() | nil,
    :op => String.t | nil,
    :value => integer() | nil
  }

  def decode(value) do
    value
  end
end
