# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerStatus do
  @moduledoc """
  represents the status of a container.
  """

  @derive Jason.Encoder
  defstruct [
    :ContainerID,
    :PID,
    :ExitCode
  ]

  @type t :: %__MODULE__{
    :ContainerID => String.t | nil,
    :PID => integer() | nil,
    :ExitCode => integer() | nil
  }

  def decode(value) do
    value
  end
end
