# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerTopResponse do
  @moduledoc """
  Container \"top\" response.
  """

  @derive Jason.Encoder
  defstruct [
    :Titles,
    :Processes
  ]

  @type t :: %__MODULE__{
    :Titles => [String.t] | nil,
    :Processes => [[String.t]] | nil
  }

  def decode(value) do
    value
  end
end
