# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerCpuUsage do
  @moduledoc """
  All CPU stats aggregated since container inception.
  """

  @derive Jason.Encoder
  defstruct [
    :total_usage,
    :percpu_usage,
    :usage_in_kernelmode,
    :usage_in_usermode
  ]

  @type t :: %__MODULE__{
    :total_usage => integer() | nil,
    :percpu_usage => [integer()] | nil,
    :usage_in_kernelmode => integer() | nil,
    :usage_in_usermode => integer() | nil
  }

  def decode(value) do
    value
  end
end
