# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerStatsResponse do
  @moduledoc """
  Statistics sample for a container.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :os_type,
    :read,
    :cpu_stats,
    :memory_stats,
    :networks,
    :pids_stats,
    :blkio_stats,
    :num_procs,
    :storage_stats,
    :preread,
    :precpu_stats
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :name => String.t | nil,
    :os_type => String.t | nil,
    :read => DateTime.t | nil,
    :cpu_stats => DockerEngineAPI.Model.ContainerCpuStats.t | nil,
    :memory_stats => DockerEngineAPI.Model.ContainerMemoryStats.t | nil,
    :networks => map() | nil,
    :pids_stats => DockerEngineAPI.Model.ContainerPidsStats.t | nil,
    :blkio_stats => DockerEngineAPI.Model.ContainerBlkioStats.t | nil,
    :num_procs => integer() | nil,
    :storage_stats => DockerEngineAPI.Model.ContainerStorageStats.t | nil,
    :preread => DateTime.t | nil,
    :precpu_stats => DockerEngineAPI.Model.ContainerCpuStats.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:cpu_stats, :struct, DockerEngineAPI.Model.ContainerCpuStats)
     |> Deserializer.deserialize(:memory_stats, :struct, DockerEngineAPI.Model.ContainerMemoryStats)
     |> Deserializer.deserialize(:pids_stats, :struct, DockerEngineAPI.Model.ContainerPidsStats)
     |> Deserializer.deserialize(:blkio_stats, :struct, DockerEngineAPI.Model.ContainerBlkioStats)
     |> Deserializer.deserialize(:storage_stats, :struct, DockerEngineAPI.Model.ContainerStorageStats)
     |> Deserializer.deserialize(:precpu_stats, :struct, DockerEngineAPI.Model.ContainerCpuStats)
  end
end
