# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerSummaryHostConfig do
  @moduledoc """
  Summary of host-specific runtime information of the container. This is a reduced set of information in the container's \"HostConfig\" as available in the container \"inspect\" response.
  """

  @derive Jason.Encoder
  defstruct [
    :NetworkMode,
    :Annotations
  ]

  @type t :: %__MODULE__{
    :NetworkMode => String.t | nil,
    :Annotations => %{optional(String.t) => String.t} | nil
  }

  def decode(value) do
    value
  end
end
