# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerStorageStats do
  @moduledoc """
  StorageStats is the disk I/O stats for read/write on Windows.  This type is Windows-specific and omitted for Linux containers.
  """

  @derive JSON.Encoder
  defstruct [
    :read_count_normalized,
    :read_size_bytes,
    :write_count_normalized,
    :write_size_bytes
  ]

  @type t :: %__MODULE__{
    :read_count_normalized => integer() | nil,
    :read_size_bytes => integer() | nil,
    :write_count_normalized => integer() | nil,
    :write_size_bytes => integer() | nil
  }

  def decode(value) do
    value
  end
end
