# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerSummaryNetworkSettings do
  @moduledoc """
  Summary of the container's network settings
  """

  @derive Jason.Encoder
  defstruct [
    :Networks
  ]

  @type t :: %__MODULE__{
    :Networks => %{optional(String.t) => DockerEngineAPI.Model.EndpointSettings.t} | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Networks, :map, DockerEngineAPI.Model.EndpointSettings)
  end
end
