# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerMemoryStats do
  @moduledoc """
  Aggregates all memory stats since container inception on Linux. Windows returns stats for commit and private working set only.
  """

  @derive JSON.Encoder
  defstruct [
    :usage,
    :max_usage,
    :stats,
    :failcnt,
    :limit,
    :commitbytes,
    :commitpeakbytes,
    :privateworkingset
  ]

  @type t :: %__MODULE__{
    :usage => integer() | nil,
    :max_usage => integer() | nil,
    :stats => %{optional(String.t) => integer()} | nil,
    :failcnt => integer() | nil,
    :limit => integer() | nil,
    :commitbytes => integer() | nil,
    :commitpeakbytes => integer() | nil,
    :privateworkingset => integer() | nil
  }

  def decode(value) do
    value
  end
end
