# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.DeviceInfo do
  @moduledoc """
  DeviceInfo represents a device that can be used by a container.
  """

  @derive JSON.Encoder
  defstruct [
    :Source,
    :ID
  ]

  @type t :: %__MODULE__{
    :Source => String.t | nil,
    :ID => String.t | nil
  }

  def decode(value) do
    value
  end
end
