# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ExecStartConfig do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :Detach,
    :Tty,
    :ConsoleSize
  ]

  @type t :: %__MODULE__{
    :Detach => boolean() | nil,
    :Tty => boolean() | nil,
    :ConsoleSize => [integer()] | nil
  }

  def decode(value) do
    value
  end
end
