# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.FirewallInfo do
  @moduledoc """
  Information about the daemon's firewalling configuration.  This field is currently only used on Linux, and omitted on other platforms.
  """

  @derive JSON.Encoder
  defstruct [
    :Driver,
    :Info
  ]

  @type t :: %__MODULE__{
    :Driver => String.t | nil,
    :Info => [[String.t]] | nil
  }

  def decode(value) do
    value
  end
end
