# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.GenericResourcesInnerDiscreteResourceSpec do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :Kind,
    :Value
  ]

  @type t :: %__MODULE__{
    :Kind => String.t | nil,
    :Value => integer() | nil
  }

  def decode(value) do
    value
  end
end
