# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.HealthConfig do
  @moduledoc """
  A test to perform to check that the container is healthy.
  """

  @derive Jason.Encoder
  defstruct [
    :Test,
    :Interval,
    :Timeout,
    :Retries,
    :StartPeriod,
    :StartInterval
  ]

  @type t :: %__MODULE__{
    :Test => [String.t] | nil,
    :Interval => integer() | nil,
    :Timeout => integer() | nil,
    :Retries => integer() | nil,
    :StartPeriod => integer() | nil,
    :StartInterval => integer() | nil
  }

  def decode(value) do
    value
  end
end
