# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Identity do
  @moduledoc """
  Identity holds information about the identity and origin of the image. This is trusted information verified by the daemon and cannot be modified by tagging an image to a different name.
  """

  @derive JSON.Encoder
  defstruct [
    :Signature,
    :Pull,
    :Build
  ]

  @type t :: %__MODULE__{
    :Signature => [DockerEngineAPI.Model.SignatureIdentity.t] | nil,
    :Pull => [DockerEngineAPI.Model.PullIdentity.t] | nil,
    :Build => [DockerEngineAPI.Model.BuildIdentity.t] | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Signature, :list, DockerEngineAPI.Model.SignatureIdentity)
     |> Deserializer.deserialize(:Pull, :list, DockerEngineAPI.Model.PullIdentity)
     |> Deserializer.deserialize(:Build, :list, DockerEngineAPI.Model.BuildIdentity)
  end
end
