# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ImageId do
  @moduledoc """
  Image ID or Digest
  """

  @derive JSON.Encoder
  defstruct [
    :ID
  ]

  @type t :: %__MODULE__{
    :ID => String.t | nil
  }

  def decode(value) do
    value
  end
end
