# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ImageSearchResponseItem do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :description,
    :is_official,
    :is_automated,
    :name,
    :star_count
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :is_official => boolean() | nil,
    :is_automated => boolean() | nil,
    :name => String.t | nil,
    :star_count => integer() | nil
  }

  def decode(value) do
    value
  end
end
