# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ImageManifestSummaryImageData do
  @moduledoc """
  The image data for the image manifest. This field is only populated when Kind is \"image\".
  """

  @derive JSON.Encoder
  defstruct [
    :Platform,
    :Containers,
    :Size
  ]

  @type t :: %__MODULE__{
    :Platform => DockerEngineAPI.Model.OciPlatform.t | nil,
    :Containers => [String.t],
    :Size => DockerEngineAPI.Model.ImageManifestSummaryImageDataSize.t
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Platform, :struct, DockerEngineAPI.Model.OciPlatform)
     |> Deserializer.deserialize(:Size, :struct, DockerEngineAPI.Model.ImageManifestSummaryImageDataSize)
  end
end
