# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ImageConfig do
  @moduledoc """
  Configuration of the image. These fields are used as defaults when starting a container from the image.
  """

  @derive JSON.Encoder
  defstruct [
    :User,
    :ExposedPorts,
    :Env,
    :Cmd,
    :Healthcheck,
    :ArgsEscaped,
    :Volumes,
    :WorkingDir,
    :Entrypoint,
    :OnBuild,
    :Labels,
    :StopSignal,
    :Shell
  ]

  @type t :: %__MODULE__{
    :User => String.t | nil,
    :ExposedPorts => %{optional(String.t) => map()} | nil,
    :Env => [String.t] | nil,
    :Cmd => [String.t] | nil,
    :Healthcheck => DockerEngineAPI.Model.HealthConfig.t | nil,
    :ArgsEscaped => boolean() | nil,
    :Volumes => %{optional(String.t) => map()} | nil,
    :WorkingDir => String.t | nil,
    :Entrypoint => [String.t] | nil,
    :OnBuild => [String.t] | nil,
    :Labels => %{optional(String.t) => String.t} | nil,
    :StopSignal => String.t | nil,
    :Shell => [String.t] | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Healthcheck, :struct, DockerEngineAPI.Model.HealthConfig)
  end
end
