# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ImageManifestSummaryImageDataSize do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :Unpacked
  ]

  @type t :: %__MODULE__{
    :Unpacked => integer()
  }

  def decode(value) do
    value
  end
end
