# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ImageManifestSummarySize do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :Total,
    :Content
  ]

  @type t :: %__MODULE__{
    :Total => integer(),
    :Content => integer()
  }

  def decode(value) do
    value
  end
end
