# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ImageSummary do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :Id,
    :ParentId,
    :RepoTags,
    :RepoDigests,
    :Created,
    :Size,
    :SharedSize,
    :VirtualSize,
    :Labels,
    :Containers,
    :Manifests,
    :Descriptor
  ]

  @type t :: %__MODULE__{
    :Id => String.t,
    :ParentId => String.t,
    :RepoTags => [String.t],
    :RepoDigests => [String.t],
    :Created => integer(),
    :Size => integer(),
    :SharedSize => integer(),
    :VirtualSize => integer() | nil,
    :Labels => %{optional(String.t) => String.t},
    :Containers => integer(),
    :Manifests => [DockerEngineAPI.Model.ImageManifestSummary.t] | nil,
    :Descriptor => DockerEngineAPI.Model.OciDescriptor.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Manifests, :list, DockerEngineAPI.Model.ImageManifestSummary)
     |> Deserializer.deserialize(:Descriptor, :struct, DockerEngineAPI.Model.OciDescriptor)
  end
end
