# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ImageManifestSummary do
  @moduledoc """
  ImageManifestSummary represents a summary of an image manifest.
  """

  @derive JSON.Encoder
  defstruct [
    :ID,
    :Descriptor,
    :Available,
    :Size,
    :Kind,
    :ImageData,
    :AttestationData
  ]

  @type t :: %__MODULE__{
    :ID => String.t,
    :Descriptor => DockerEngineAPI.Model.OciDescriptor.t,
    :Available => boolean(),
    :Size => DockerEngineAPI.Model.ImageManifestSummarySize.t,
    :Kind => String.t,
    :ImageData => DockerEngineAPI.Model.ImageManifestSummaryImageData.t | nil,
    :AttestationData => DockerEngineAPI.Model.ImageManifestSummaryAttestationData.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Descriptor, :struct, DockerEngineAPI.Model.OciDescriptor)
     |> Deserializer.deserialize(:Size, :struct, DockerEngineAPI.Model.ImageManifestSummarySize)
     |> Deserializer.deserialize(:ImageData, :struct, DockerEngineAPI.Model.ImageManifestSummaryImageData)
     |> Deserializer.deserialize(:AttestationData, :struct, DockerEngineAPI.Model.ImageManifestSummaryAttestationData)
  end
end
