# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.IpamStatus do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :Subnets
  ]

  @type t :: %__MODULE__{
    :Subnets => %{optional(String.t) => DockerEngineAPI.Model.SubnetStatus.t} | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Subnets, :map, DockerEngineAPI.Model.SubnetStatus)
  end
end
