# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.KnownSignerIdentity do
  @moduledoc """
  KnownSignerIdentity is an identifier for a special signer identity that is known to the implementation.
  """

  @derive JSON.Encoder
  defstruct [

  ]

  @type t :: %__MODULE__{

  }

  def decode(value) do
    value
  end
end
