# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.MountPoint do
  @moduledoc """
  MountPoint represents a mount point configuration inside the container. This is used for reporting the mountpoints in use by a container.
  """

  @derive JSON.Encoder
  defstruct [
    :Type,
    :Name,
    :Source,
    :Destination,
    :Driver,
    :Mode,
    :RW,
    :Propagation
  ]

  @type t :: %__MODULE__{
    :Type => DockerEngineAPI.Model.MountType.t | nil,
    :Name => String.t | nil,
    :Source => String.t | nil,
    :Destination => String.t | nil,
    :Driver => String.t | nil,
    :Mode => String.t | nil,
    :RW => boolean() | nil,
    :Propagation => String.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Type, :struct, DockerEngineAPI.Model.MountType)
  end
end
