# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.MountImageOptions do
  @moduledoc """
  Optional configuration for the `image` type.
  """

  @derive Jason.Encoder
  defstruct [
    :Subpath
  ]

  @type t :: %__MODULE__{
    :Subpath => String.t | nil
  }

  def decode(value) do
    value
  end
end
