# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.MountTmpfsOptions do
  @moduledoc """
  Optional configuration for the `tmpfs` type.
  """

  @derive Jason.Encoder
  defstruct [
    :SizeBytes,
    :Mode,
    :Options
  ]

  @type t :: %__MODULE__{
    :SizeBytes => integer() | nil,
    :Mode => integer() | nil,
    :Options => [[String.t]] | nil
  }

  def decode(value) do
    value
  end
end
