# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.MountType do
  @moduledoc """
  The mount type. Available types:  - `bind` a mount of a file or directory from the host into the container. - `cluster` a Swarm cluster volume. - `image` an OCI image. - `npipe` a named pipe from the host into the container. - `tmpfs` a `tmpfs`. - `volume` a docker volume with the given `Name`.
  """

  @derive JSON.Encoder
  defstruct [

  ]

  @type t :: %__MODULE__{

  }

  def decode(value) do
    value
  end
end
