# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Network do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :Name,
    :Id,
    :Created,
    :Scope,
    :Driver,
    :EnableIPv4,
    :EnableIPv6,
    :IPAM,
    :Internal,
    :Attachable,
    :Ingress,
    :ConfigFrom,
    :ConfigOnly,
    :Containers,
    :Options,
    :Labels,
    :Peers
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil,
    :Id => String.t | nil,
    :Created => String.t | nil,
    :Scope => String.t | nil,
    :Driver => String.t | nil,
    :EnableIPv4 => boolean() | nil,
    :EnableIPv6 => boolean() | nil,
    :IPAM => DockerEngineAPI.Model.Ipam.t | nil,
    :Internal => boolean() | nil,
    :Attachable => boolean() | nil,
    :Ingress => boolean() | nil,
    :ConfigFrom => DockerEngineAPI.Model.ConfigReference.t | nil,
    :ConfigOnly => boolean() | nil,
    :Containers => %{optional(String.t) => DockerEngineAPI.Model.NetworkContainer.t} | nil,
    :Options => %{optional(String.t) => String.t} | nil,
    :Labels => %{optional(String.t) => String.t} | nil,
    :Peers => [DockerEngineAPI.Model.PeerInfo.t] | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:IPAM, :struct, DockerEngineAPI.Model.Ipam)
     |> Deserializer.deserialize(:ConfigFrom, :struct, DockerEngineAPI.Model.ConfigReference)
     |> Deserializer.deserialize(:Containers, :map, DockerEngineAPI.Model.NetworkContainer)
     |> Deserializer.deserialize(:Peers, :list, DockerEngineAPI.Model.PeerInfo)
  end
end
