# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.NetworkTaskInfo do
  @moduledoc """
  carries the information about one backend task
  """

  @derive JSON.Encoder
  defstruct [
    :Name,
    :EndpointID,
    :EndpointIP,
    :Info
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil,
    :EndpointID => String.t | nil,
    :EndpointIP => String.t | nil,
    :Info => %{optional(String.t) => String.t} | nil
  }

  def decode(value) do
    value
  end
end
