# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.NetworkDisconnectRequest do
  @moduledoc """
  NetworkDisconnectRequest represents the data to be used to disconnect a container from a network.
  """

  @derive JSON.Encoder
  defstruct [
    :Container,
    :Force
  ]

  @type t :: %__MODULE__{
    :Container => String.t,
    :Force => boolean() | nil
  }

  def decode(value) do
    value
  end
end
