# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.NetworkStatus do
  @moduledoc """
  provides runtime information about the network such as the number of allocated IPs.
  """

  @derive JSON.Encoder
  defstruct [
    :IPAM
  ]

  @type t :: %__MODULE__{
    :IPAM => DockerEngineAPI.Model.IpamStatus.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:IPAM, :struct, DockerEngineAPI.Model.IpamStatus)
  end
end
