# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.NetworkPruneResponse do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :NetworksDeleted
  ]

  @type t :: %__MODULE__{
    :NetworksDeleted => [String.t] | nil
  }

  def decode(value) do
    value
  end
end
