# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.NetworkSettings do
  @moduledoc """
  NetworkSettings exposes the network settings in the API
  """

  @derive JSON.Encoder
  defstruct [
    :SandboxID,
    :SandboxKey,
    :Ports,
    :Networks
  ]

  @type t :: %__MODULE__{
    :SandboxID => String.t | nil,
    :SandboxKey => String.t | nil,
    :Ports => %{optional(String.t) => [DockerEngineAPI.Model.PortBinding.t]} | nil,
    :Networks => %{optional(String.t) => DockerEngineAPI.Model.EndpointSettings.t} | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Networks, :map, DockerEngineAPI.Model.EndpointSettings)
  end
end
