# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.NriInfo do
  @moduledoc """
  Information about the Node Resource Interface (NRI).  This field is only present if NRI is enabled.
  """

  @derive JSON.Encoder
  defstruct [
    :Info
  ]

  @type t :: %__MODULE__{
    :Info => [[String.t]] | nil
  }

  def decode(value) do
    value
  end
end
