# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.OciDescriptor do
  @moduledoc """
  A descriptor struct containing digest, media type, and size, as defined in the [OCI Content Descriptors Specification](https://github.com/opencontainers/image-spec/blob/v1.0.1/descriptor.md).
  """

  @derive Jason.Encoder
  defstruct [
    :mediaType,
    :digest,
    :size,
    :urls,
    :annotations,
    :data,
    :platform,
    :artifactType
  ]

  @type t :: %__MODULE__{
    :mediaType => String.t | nil,
    :digest => String.t | nil,
    :size => integer() | nil,
    :urls => [String.t] | nil,
    :annotations => %{optional(String.t) => String.t} | nil,
    :data => String.t | nil,
    :platform => DockerEngineAPI.Model.OciPlatform.t | nil,
    :artifactType => String.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:platform, :struct, DockerEngineAPI.Model.OciPlatform)
  end
end
