# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PeerInfo do
  @moduledoc """
  PeerInfo represents one peer of an overlay network.
  """

  @derive Jason.Encoder
  defstruct [
    :Name,
    :IP
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil,
    :IP => String.t | nil
  }

  def decode(value) do
    value
  end
end
