# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PluginConfigRootfs do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :diff_ids
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil,
    :diff_ids => [String.t] | nil
  }

  def decode(value) do
    value
  end
end
