# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PluginConfigInterface do
  @moduledoc """
  The interface between Docker and the plugin
  """

  @derive JSON.Encoder
  defstruct [
    :Types,
    :Socket,
    :ProtocolScheme
  ]

  @type t :: %__MODULE__{
    :Types => [String.t],
    :Socket => String.t,
    :ProtocolScheme => String.t | nil
  }

  def decode(value) do
    value
  end
end
