# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PortStatus do
  @moduledoc """
  represents the port status of a task's host ports whose service has published host ports
  """

  @derive JSON.Encoder
  defstruct [
    :Ports
  ]

  @type t :: %__MODULE__{
    :Ports => [DockerEngineAPI.Model.EndpointPortConfig.t] | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Ports, :list, DockerEngineAPI.Model.EndpointPortConfig)
  end
end
