# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PortSummary do
  @moduledoc """
  Describes a port-mapping between the container and the host.
  """

  @derive JSON.Encoder
  defstruct [
    :IP,
    :PrivatePort,
    :PublicPort,
    :Type
  ]

  @type t :: %__MODULE__{
    :IP => String.t | nil,
    :PrivatePort => integer(),
    :PublicPort => integer() | nil,
    :Type => String.t
  }

  def decode(value) do
    value
  end
end
