# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PullIdentity do
  @moduledoc """
  PullIdentity contains remote location information if image was created via pull. If image was pulled via mirror, this contains the original repository location.
  """

  @derive JSON.Encoder
  defstruct [
    :Repository
  ]

  @type t :: %__MODULE__{
    :Repository => String.t | nil
  }

  def decode(value) do
    value
  end
end
