# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.RootFsStorage do
  @moduledoc """
  Information about the storage used for the container's root filesystem.
  """

  @derive JSON.Encoder
  defstruct [
    :Snapshot
  ]

  @type t :: %__MODULE__{
    :Snapshot => DockerEngineAPI.Model.RootFsStorageSnapshot.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Snapshot, :struct, DockerEngineAPI.Model.RootFsStorageSnapshot)
  end
end
