# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.RootFsStorageSnapshot do
  @moduledoc """
  Information about a snapshot backend of the container's root filesystem.
  """

  @derive JSON.Encoder
  defstruct [
    :Name
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil
  }

  def decode(value) do
    value
  end
end
