# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ServiceCreateResponse do
  @moduledoc """
  contains the information returned to a client on the creation of a new service.
  """

  @derive JSON.Encoder
  defstruct [
    :ID,
    :Warnings
  ]

  @type t :: %__MODULE__{
    :ID => String.t | nil,
    :Warnings => [String.t] | nil
  }

  def decode(value) do
    value
  end
end
