# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ServiceInfo do
  @moduledoc """
  represents service parameters with the list of service's tasks
  """

  @derive JSON.Encoder
  defstruct [
    :VIP,
    :Ports,
    :LocalLBIndex,
    :Tasks
  ]

  @type t :: %__MODULE__{
    :VIP => String.t | nil,
    :Ports => [String.t] | nil,
    :LocalLBIndex => integer() | nil,
    :Tasks => [DockerEngineAPI.Model.NetworkTaskInfo.t] | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Tasks, :list, DockerEngineAPI.Model.NetworkTaskInfo)
  end
end
