# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SignerIdentity do
  @moduledoc """
  SignerIdentity contains information about the signer certificate used to sign the image.
  """

  @derive JSON.Encoder
  defstruct [
    :CertificateIssuer,
    :SubjectAlternativeName,
    :Issuer,
    :BuildSignerURI,
    :BuildSignerDigest,
    :RunnerEnvironment,
    :SourceRepositoryURI,
    :SourceRepositoryDigest,
    :SourceRepositoryRef,
    :SourceRepositoryIdentifier,
    :SourceRepositoryOwnerURI,
    :SourceRepositoryOwnerIdentifier,
    :BuildConfigURI,
    :BuildConfigDigest,
    :BuildTrigger,
    :RunInvocationURI,
    :SourceRepositoryVisibilityAtSigning
  ]

  @type t :: %__MODULE__{
    :CertificateIssuer => String.t | nil,
    :SubjectAlternativeName => String.t | nil,
    :Issuer => String.t | nil,
    :BuildSignerURI => String.t | nil,
    :BuildSignerDigest => String.t | nil,
    :RunnerEnvironment => String.t | nil,
    :SourceRepositoryURI => String.t | nil,
    :SourceRepositoryDigest => String.t | nil,
    :SourceRepositoryRef => String.t | nil,
    :SourceRepositoryIdentifier => String.t | nil,
    :SourceRepositoryOwnerURI => String.t | nil,
    :SourceRepositoryOwnerIdentifier => String.t | nil,
    :BuildConfigURI => String.t | nil,
    :BuildConfigDigest => String.t | nil,
    :BuildTrigger => String.t | nil,
    :RunInvocationURI => String.t | nil,
    :SourceRepositoryVisibilityAtSigning => String.t | nil
  }

  def decode(value) do
    value
  end
end
