# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SignatureTimestamp do
  @moduledoc """
  SignatureTimestamp contains information about a verified signed timestamp for an image signature.
  """

  @derive JSON.Encoder
  defstruct [
    :Type,
    :URI,
    :Timestamp
  ]

  @type t :: %__MODULE__{
    :Type => DockerEngineAPI.Model.SignatureTimestampType.t | nil,
    :URI => String.t | nil,
    :Timestamp => DateTime.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Type, :struct, DockerEngineAPI.Model.SignatureTimestampType)
  end
end
