# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SignatureTimestampType do
  @moduledoc """
  SignatureTimestampType is the type of timestamp used in the signature.
  """

  @derive JSON.Encoder
  defstruct [

  ]

  @type t :: %__MODULE__{

  }

  def decode(value) do
    value
  end
end
