# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SignatureIdentity do
  @moduledoc """
  SignatureIdentity contains the properties of verified signatures for the image.
  """

  @derive JSON.Encoder
  defstruct [
    :Name,
    :Timestamps,
    :KnownSigner,
    :DockerReference,
    :Signer,
    :SignatureType,
    :Error,
    :Warnings
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil,
    :Timestamps => [DockerEngineAPI.Model.SignatureTimestamp.t] | nil,
    :KnownSigner => DockerEngineAPI.Model.KnownSignerIdentity.t | nil,
    :DockerReference => String.t | nil,
    :Signer => DockerEngineAPI.Model.SignerIdentity.t | nil,
    :SignatureType => DockerEngineAPI.Model.SignatureType.t | nil,
    :Error => String.t | nil,
    :Warnings => [String.t] | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Timestamps, :list, DockerEngineAPI.Model.SignatureTimestamp)
     |> Deserializer.deserialize(:KnownSigner, :struct, DockerEngineAPI.Model.KnownSignerIdentity)
     |> Deserializer.deserialize(:Signer, :struct, DockerEngineAPI.Model.SignerIdentity)
     |> Deserializer.deserialize(:SignatureType, :struct, DockerEngineAPI.Model.SignatureType)
  end
end
