# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Storage do
  @moduledoc """
  Information about the storage used by the container.
  """

  @derive JSON.Encoder
  defstruct [
    :RootFS
  ]

  @type t :: %__MODULE__{
    :RootFS => DockerEngineAPI.Model.RootFsStorage.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:RootFS, :struct, DockerEngineAPI.Model.RootFsStorage)
  end
end
