# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SubnetStatus do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :IPsInUse,
    :DynamicIPsAvailable
  ]

  @type t :: %__MODULE__{
    :IPsInUse => integer() | nil,
    :DynamicIPsAvailable => integer() | nil
  }

  def decode(value) do
    value
  end
end
