# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SystemDataUsageResponse do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :ImageUsage,
    :ContainerUsage,
    :VolumeUsage,
    :BuildCacheUsage
  ]

  @type t :: %__MODULE__{
    :ImageUsage => DockerEngineAPI.Model.ImagesDiskUsage.t | nil,
    :ContainerUsage => DockerEngineAPI.Model.ContainersDiskUsage.t | nil,
    :VolumeUsage => DockerEngineAPI.Model.VolumesDiskUsage.t | nil,
    :BuildCacheUsage => DockerEngineAPI.Model.BuildCacheDiskUsage.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:ImageUsage, :struct, DockerEngineAPI.Model.ImagesDiskUsage)
     |> Deserializer.deserialize(:ContainerUsage, :struct, DockerEngineAPI.Model.ContainersDiskUsage)
     |> Deserializer.deserialize(:VolumeUsage, :struct, DockerEngineAPI.Model.VolumesDiskUsage)
     |> Deserializer.deserialize(:BuildCacheUsage, :struct, DockerEngineAPI.Model.BuildCacheDiskUsage)
  end
end
