# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskSpecContainerSpecPrivileges do
  @moduledoc """
  Security options for the container
  """

  @derive Jason.Encoder
  defstruct [
    :CredentialSpec,
    :SELinuxContext,
    :Seccomp,
    :AppArmor,
    :NoNewPrivileges
  ]

  @type t :: %__MODULE__{
    :CredentialSpec => DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesCredentialSpec.t | nil,
    :SELinuxContext => DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesSeLinuxContext.t | nil,
    :Seccomp => DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesSeccomp.t | nil,
    :AppArmor => DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesAppArmor.t | nil,
    :NoNewPrivileges => boolean() | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:CredentialSpec, :struct, DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesCredentialSpec)
     |> Deserializer.deserialize(:SELinuxContext, :struct, DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesSeLinuxContext)
     |> Deserializer.deserialize(:Seccomp, :struct, DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesSeccomp)
     |> Deserializer.deserialize(:AppArmor, :struct, DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesAppArmor)
  end
end
