# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskStatus do
  @moduledoc """
  represents the status of a task.
  """

  @derive Jason.Encoder
  defstruct [
    :Timestamp,
    :State,
    :Message,
    :Err,
    :ContainerStatus,
    :PortStatus
  ]

  @type t :: %__MODULE__{
    :Timestamp => String.t | nil,
    :State => DockerEngineAPI.Model.TaskState.t | nil,
    :Message => String.t | nil,
    :Err => String.t | nil,
    :ContainerStatus => DockerEngineAPI.Model.ContainerStatus.t | nil,
    :PortStatus => DockerEngineAPI.Model.PortStatus.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:State, :struct, DockerEngineAPI.Model.TaskState)
     |> Deserializer.deserialize(:ContainerStatus, :struct, DockerEngineAPI.Model.ContainerStatus)
     |> Deserializer.deserialize(:PortStatus, :struct, DockerEngineAPI.Model.PortStatus)
  end
end
