# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ThrottleDevice do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :Path,
    :Rate
  ]

  @type t :: %__MODULE__{
    :Path => String.t | nil,
    :Rate => integer() | nil
  }

  def decode(value) do
    value
  end
end
