# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Topology do
  @moduledoc """
  A map of topological domains to topological segments. For in depth details, see documentation for the Topology object in the CSI specification.
  """

  @derive JSON.Encoder
  defstruct [
    :Segments
  ]

  @type t :: %__MODULE__{
    :Segments => %{optional(String.t) => String.t} | nil
  }

  def decode(value) do
    value
  end
end
